version: '3.8'

services:
  api:
    build: .
    container_name: transactions-api
    restart: on-failure
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ['CMD', 'curl', '-f', '${BASE_URL}/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - .:/app
    command: yarn start:dev
