version: '3.8'

services:
  api:
    build: .
    container_name: transactions-api
    restart: on-failure
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ['CMD', 'curl', '-f', '${BASE_URL}/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - monitoring
    volumes:
      - .:/app
    command: yarn start:dev

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
