services:
  api:
    build: .
    container_name: transactions-api
    restart: on-failure
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', '${BASE_URL}/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - monitoring
    volumes:
      - .:/app
    command: yarn start:dev

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT}:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  monitoring:

volumes:
  grafana-data:
