version: '3.8'

services:
  api:
    build: .
    container_name: transactions-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: yarn start:dev
