version: '3.8'

services:
  api:
    build: .
    container_name: transactions-api
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: yarn start:dev
